package co.edu.unicauca.mvc.vistas;

import co.edu.unicauca.mvc.accesoADatos.ArticuloRepositorio;
import co.edu.unicauca.mvc.accesoADatos.AutorRepositorio;
import co.edu.unicauca.mvc.accesoADatos.ConferenciaRepositorio;
import co.edu.unicauca.mvc.accesoADatos.EvaluadorRepositorio;
import co.edu.unicauca.mvc.accesoADatos.OrganizadorRepositorio;
import co.edu.unicauca.mvc.controladores.ArticuloServicio;
import co.edu.unicauca.mvc.controladores.AutorServicio;
import co.edu.unicauca.mvc.controladores.ConferenciaServicio;
import co.edu.unicauca.mvc.controladores.EvaluadorServicio;
import co.edu.unicauca.mvc.controladores.OrganizadorServicio;
import co.edu.unicauca.mvc.vistas.adminConferencia.VtnPrincipalAdmin;

/**
 * Clase VtnLogin que representa la ventana principal de login de la aplicación.
 * Hereda de javax.swing.JFrame para crear una interfaz gráfica que permite a los usuarios seleccionar
 * su rol y acceder al sistema correspondiente.
 * Se inicializan los servicios necesarios y se permite al usuario seleccionar entre los roles
 * disponibles: Organizador, Autor o Evaluador.
 */

public final class VtnLogin extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    private VtnPrincipalAdmin objVtnPrincipal;
     /**
     * Constructor de la clase que inicializa los componentes gráficos y los servicios necesarios.
     */
    public VtnLogin() {
        initComponents();
        inicializarResSer();
    }
    
    /**
     * Método encargado de inicializar los repositorios y servicios de la aplicación.
     * Se asocian los servicios a la ventana principal del administrador.
     */
    public void inicializarResSer() {
        ConferenciaRepositorio objRConferencia = new ConferenciaRepositorio();
        ConferenciaServicio objSConferencia 
                = new ConferenciaServicio(objRConferencia);

        ArticuloRepositorio objRArticulo = new ArticuloRepositorio();
        ArticuloServicio objSArticulo = new ArticuloServicio(objRArticulo);

        OrganizadorRepositorio objROrganizador = new OrganizadorRepositorio();
        OrganizadorServicio objSOrganizador
                = new OrganizadorServicio(objROrganizador);

        EvaluadorRepositorio objREvaluador = new EvaluadorRepositorio();
        EvaluadorServicio objSEvaluador = new EvaluadorServicio(objREvaluador);

        AutorRepositorio objRAutor = new AutorRepositorio();
        AutorServicio objSAutor = new AutorServicio(objRAutor);

        this.objVtnPrincipal = new VtnPrincipalAdmin();
        objVtnPrincipal.asociarServios(objSConferencia, objSArticulo, 
                objSOrganizador, objSEvaluador, objSAutor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbRol = new javax.swing.JComboBox<>();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));

        cmbRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Rol", "Organizador", "Autor", "Evaluador" }));
        cmbRol.setToolTipText("");
        cmbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     /**
     * Método que maneja el evento de selección de rol en el comboBox.
     * Dependiendo del rol seleccionado, abre la ventana principal correspondiente.
     */
    private void cmbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolActionPerformed
        String opcion = (String) cmbRol.getSelectedItem();
        if (!opcion.equals("Seleccione Rol")) {
            objVtnPrincipal.gestionRol(opcion);
            objVtnPrincipal.setVisible(true);
        } else {
            lblResultado.setText("Seleccione un rol válido");
        }
    }//GEN-LAST:event_cmbRolActionPerformed

    /**
     * Método principal que inicia la ejecución de la ventana de login.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VtnLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables
}
